title: Elijah Tabachnik
email: elijah.tabachnik@gmail.com
description: >-
  My name is Elijah Tabachnik, I'm an aspiring Game Developer studying Computer Science at UCI.
  I love strategy games, hiking and of course making games.
baseurl: "" # for GitHub Pages repo root
url: "https://elijahtab.github.io"

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
    
defaults:
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true


remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache

minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"


markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: "/page:num"

author:
  name: "Elijah Tabachnik"
  avatar: "/assets/images/avatar.png"  
  bio: "Game Developer. AI Enthusiast. Hiker."
  location: "Irvine, CA"
  links:
    - label: "GitHub"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/elijahtab"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:elijah.tabachnik@gmail.com"
    - label: "Resume"
      icon: "fas fa-file-alt"
      url: "/assets/files/resume.pdf"

      

header:
  navigation: true
